import { chakra, Flex, Heading, Image, Text, Button } from '@chakra-ui/react';
import { NextPage } from 'next';
import Head from 'next/head';
import NextImage from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/Header/Header';
import Container from '../components/Container/Container';
import { useEffect } from 'react';
import useIsDarkMode from '../utils/useIsDarkMode';
import { ArrowForwardIcon } from '@chakra-ui/icons';
import Link from '../components/Link/Link';

const Home: NextPage = () => {
	const Avatar = chakra(NextImage, {
		shouldForwardProp: (prop) => [ 'width', 'height', 'src', 'alt' ].includes(prop)
	});

	const isDark = useIsDarkMode();

	return (
		<div>
			<Head>
				<title>Nelson Ha</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container>
				<Flex
					h={'80vh'}
					className={styles.bioContainer}
					flexDir={'column'}
					alignItems={'center'}
					justify={'center'}
				>
					<Flex flexDir={'column'} alignItems={'center'} py={10} h={'40%'} justify={'space-evenly'}>
						<Image
							// className={isDark && 'grayscale'}
							src="/avatar.jpg"
							boxSize={{ base: '120px', md: '160px' }}
							alt="te"
							borderRadius={'full'}
						/>
						{/* <Avatar src="/avatar.jpg" alt="Nelson Ha" width={120} height={120} borderRadius="full" /> */}
						<Heading as={'h1'} size={'3xl'} textAlign={'center'}>
							Nelson Ha
						</Heading>
						<Heading as={'h2'} size={'md'} fontWeight={'medium'} opacity={0.95} textAlign={'center'}>
							Software Engineer at <chakra.span fontWeight={'semibold'}>Commonwealth Bank</chakra.span>
						</Heading>
					</Flex>
					<Text maxW={'75%'}>
						I'm a full-stack software engineer with 3 years experience currently working at Commonwealth
						Bank.{' '}
						<Button variant={'link'} rightIcon={<ArrowForwardIcon />}>
							<Link href="/about">Learn more about me </Link>
						</Button>
					</Text>
					<Flex mt={12}>
						<Button variant={'ghost'}>Contact Me</Button>
						<Button variant={'solid'}>Whatsapp phone?</Button>
					</Flex>
				</Flex>
			</Container>
		</div>
	);
};

export default Home;
