import { Button } from '@chakra-ui/react';
import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import Container from '../components/Container';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Nelson Ha</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Container>Overview content stuff</Container>
		</div>
	);
};

export default Home;
